<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hubungi Kami_mx-image</name>
   <tag></tag>
   <elementGuidId>378a4b43-ea2d-490e-a0b1-c3504c223bd1</elementGuidId>
   <imagePath>../../Downloads/Section-Utama.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../Downloads/Section-Utama.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.mx-personal-branding-image > img.mx-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mx-page-block-1']/div[2]/div/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mx-page-block-1 img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0faea50c-0589-435e-b879-79729741dbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-image</value>
      <webElementGuid>af578292-6bab-494d-8991-6f2c6e9ba3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://maxpage.staging.ittron.co.id/application/maxpage/default/files/media/cuanq.mp.cerdaskreatif.co.id/files/Section-Utama.png</value>
      <webElementGuid>a78fba1a-88f1-443b-8829-f2d5342e9f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mx-page-block-1&quot;)/div[@class=&quot;mx-page-block-wrapper&quot;]/div[@class=&quot;mx-block mx-personal-branding&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-6 mx-personal-branding-image&quot;]/img[@class=&quot;mx-image&quot;]</value>
      <webElementGuid>256b722c-0e8e-44f8-9649-675ca2ffe488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mx-page-block-1']/div[2]/div/div/div/div[2]/img</value>
      <webElementGuid>753842f6-7561-461a-947a-603f492244bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://maxpage.staging.ittron.co.id/application/maxpage/default/files/media/cuanq.mp.cerdaskreatif.co.id/files/Section-Utama.png')]</value>
      <webElementGuid>8e238e80-61de-4c5e-9362-7f0fafe6f21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>d06ce492-ad5f-4bc7-89b3-e169c82b6d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://maxpage.staging.ittron.co.id/application/maxpage/default/files/media/cuanq.mp.cerdaskreatif.co.id/files/Section-Utama.png']</value>
      <webElementGuid>9fedb75e-6e6a-4d54-b444-c698d03e0f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
