<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Beranda_mx-image</name>
   <tag></tag>
   <elementGuidId>8593f987-d0a8-41d6-ba37-69fcae1026cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mx-navbar-builder']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mx-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logo Image&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ccf769a-ae61-48e9-9cf5-5f78b9e4772b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-image</value>
      <webElementGuid>29472eca-9459-4212-b1ea-c4ff21490ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://maxpage.staging.ittron.co.id/application/maxpage/default/files/media/cuanq.mp.cerdaskreatif.co.id/files/Logo.png</value>
      <webElementGuid>6fd215d7-6c6a-4259-bc6b-26304613239e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo Image</value>
      <webElementGuid>0e4368dc-7e92-4c99-972e-507f1d1da5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mx-navbar-builder&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;mx-header-box&quot;]/div[@class=&quot;mx-logo&quot;]/a[@class=&quot;mx-logo-link&quot;]/img[@class=&quot;mx-image&quot;]</value>
      <webElementGuid>9c7c5b15-fdcb-4a75-91d9-4097949390a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mx-navbar-builder']/div/div/div/a/img</value>
      <webElementGuid>f8bd19f7-752f-413f-aeb1-f5718450022e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo Image']</value>
      <webElementGuid>2410aa58-91af-4974-a3b1-575cdc2fe5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>08a124df-a72a-4079-a5c1-0d5b5da5ae0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://maxpage.staging.ittron.co.id/application/maxpage/default/files/media/cuanq.mp.cerdaskreatif.co.id/files/Logo.png' and @alt = 'Logo Image']</value>
      <webElementGuid>fcaabd71-e782-4797-99cf-304773ef3dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
